Repository ormi3-final-project-team/nolreo_wassup_BE, pull requests merged in 2023-12, with the labels that each got.

#30 ✨ Feat: 기차 CRUD 기능 및 테스트
  traffic/serializers.py
  traffic/tests/test_bus.py
  traffic/tests/test_train.py
  traffic/urls.py
  traffic/views.py
Labels: enhancement

#34 :sparkles: Feat: 렌트카 CRUD 기능 및 테스트
  traffic/migrations/0003_alter_bus_num_alter_rentalcar_num_alter_train_num.py
  traffic/models.py
  traffic/serializers.py
  traffic/tests/test_rentalcar.py
  traffic/urls.py
  traffic/views.py
Labels: enhancement

#35 :sparkles: Feat: 사용자 프로필 조회 기능
  README.md
  account/models.py
  account/serializers.py
  account/tests.py
  account/urls.py
  account/views.py
  et HEAD~
  utils/permissions.py
Labels: enhancement

#38 :bug: Fix: lodging models.py 이미지필드 수정
  lodging/migrations/0006_alter_lodgingimage_image.py
  lodging/migrations/0007_alter_lodgingimage_image.py
  lodging/models.py
Labels: bug

#41 :sparkles: Feat: 계정 삭제
  account/migrations/0007_alter_customuser_nickname.py
  account/tests.py
Labels: enhancement

#43 ✨ Feat: 렌트카 이미지 생성, 삭제 및 테스트
  traffic/models.py
  traffic/serializers.py
  traffic/tests/test_rentalcar.py
  traffic/urls.py
  traffic/views.py
Labels: enhancement

#49 :sparkles: Feat: 숙소 이미지 API 개발, 테스트 코드 추가
  lodging/serializers.py
  lodging/tests/lodging_image_tests.py
  lodging/tests/lodging_tests.py
  lodging/urls.py
  lodging/views.py
  media/profile_image/2023/12/14/test_image.jpg
  media/profile_image/2023/12/14/test_image_9jhQW0a.jpg
  media/profile_image/2023/12/14/test_image_ifmTkfE.jpg
  media/profile_image/2023/12/14/test_image_oqTIanZ.jpg
  media/profile_image/2023/12/14/test_image_xcOhqoS.jpg
  traffic/migrations/0004_alter_bus_num_alter_rentalcar_num_alter_train_num.py
Labels: enhancement

#55 ✨ Feat: 렌트카 리뷰 CRUD 기능 및 테스트
  traffic/serializers.py
  traffic/tests/test_rentalcar.py
  traffic/urls.py
  traffic/views.py
Labels: enhancement

#57 :sparkles: Feat: 숙소 찜 목록 API
  account/views.py
  pick/tests.py
  pick/views.py
  utils/permissions.py
Labels: enhancement

#56 :sparkles: Feat: 숙소 리뷰 API 개발 및 테스트코드 작성
  lodging/serializers.py
  lodging/tests/lodging_review_tests.py
  lodging/tests/lodging_tests.py
  lodging/urls.py
  lodging/views.py
  pick/migrations/0004_remove_pick_unique_lodging_per_user_and_more.py
Labels: enhancement

#59 ✨ Feat: 숙소 찜 삭제 API
  pick/serializers.py
  pick/tests.py
  pick/views.py
Labels: enhancement

#65 :sparkles: Feat: 기차 찜 생성, 목록, 삭제, 렌트카 찜 생성, 목록 API
  README.md
  pick/serializers.py
  pick/tests.py
  pick/urls.py
  pick/views.py
Labels: enhancement

#71 :sparkles: Feat: 렌트카 삭제 API
  pick/tests.py
  pick/urls.py
  pick/views.py
Labels: enhancement

#73 🐛 Fix: 예약 테이블 관계 수정
  reservation/migrations/0004_remove_reservation_lodging_reservation_room.py
  reservation/models.py
  static/assets/images/erd.png
Labels: enhancement

#78 :bug: Fix: 버스, 기차, 렌트카 테스트 오류 수정
  lodging/tests/__init__.py
  traffic/models.py
  traffic/tests/__init__.py
  traffic/tests/test_bus.py
  traffic/tests/test_rentalcar.py
  traffic/tests/test_train.py
Labels: bug

#75 :sparkles: Feat: 객실 예약 생성 API
  pick/models.py
  pick/views.py
  reservation/migrations/0005_alter_reservation_reservation_type.py
  reservation/models.py
  reservation/serializers.py
  reservation/tests.py
  reservation/urls.py
  reservation/views.py
  utils/permissions.py
Labels: enhancement

#80 :sparkles: Feat: 숙소 예약 목록 API
  reservation/tests.py
  reservation/views.py
Labels: enhancement

#81 :sparkles: Feat: 숙소 리뷰 이미지 생성 API 개발
  lodging/serializers.py
  lodging/tests/test_lodging.py
  lodging/tests/test_lodging_image.py
  lodging/tests/test_lodging_review.py
  lodging/urls.py
  lodging/views.py
  utils/tools.py
Labels: enhancement

#86 :sparkles: Feat: 렌트카 리뷰 답글 API 개발 및 테스트
  traffic/serializers.py
  traffic/tests/test_rentalcar.py
  traffic/urls.py
  traffic/views.py
Labels: enhancement

#87 :sparkles: Feat: 숙소 예약 수정 API
  README.md
  reservation/serializers.py
  reservation/tests.py
  reservation/views.py
Labels: enhancement

#89 :sparkles: Feat: 숙소 리뷰 댓글 crud 개발
  lodging/serializers.py
  lodging/tests/test_lodging.py
  lodging/tests/test_lodging_comment.py
  lodging/tests/test_lodging_image.py
  lodging/tests/test_lodging_review.py
  lodging/tests/test_lodging_roomtype.py
  lodging/urls.py
  lodging/views.py
Labels: enhancement

#92 ✨ Feat: 객실 예약 삭제 API
  README.md
  reservation/serializers.py
  reservation/tests.py
  reservation/views.py
Labels: enhancement

#95 :sparkles: Feat: 객실 이미지 CRUD API 개발
  lodging/serializers.py
  lodging/tests/test_lodging_image.py
  lodging/tests/test_lodging_roomtype.py
  lodging/urls.py
  lodging/views.py
Labels: enhancement

#98 ✨ Feat: 숙소 편의시설 API 개발, :test_tube: Test: 테스트 코드 리팩토링
  lodging/serializers.py
  lodging/tests/test_lodging.py
  lodging/tests/test_lodging_amenity.py
  lodging/tests/test_lodging_comment.py
  lodging/tests/test_lodging_image.py
  lodging/tests/test_lodging_review.py
  lodging/tests/test_lodging_roomtype.py
  lodging/tests/test_setup.py
  lodging/urls.py
  lodging/views.py
Labels: enhancement

#99 :sparkles: Feat: 버스 예약 생성, 목록, 삭제 API & 📝 Doc: README 수정
  README.md
  reservation/serializers.py
  reservation/tests.py
  reservation/urls.py
  reservation/views.py
Labels: enhancement

#107 :sparkles: Feat: 숙소 메인, 서브 주소 API 개발
  lodging/models.py
  lodging/serializers.py
  lodging/tests/test_lodging_location.py
  lodging/tests/test_setup.py
  lodging/urls.py
  lodging/views.py
Labels: enhancement

#103 :sparkles: Feat: 기차 예약 생성, 목록, 삭제 API
  reservation/serializers.py
  reservation/tests.py
  reservation/urls.py
  reservation/views.py
Labels: enhancement

#110 :sparkles: Feat: 렌트카 예약 생성, 목록, 수정, 삭제 API
  reservation/serializers.py
  reservation/tests.py
  reservation/urls.py
  reservation/views.py
Labels: enhancement

#114 :sparkles: Feat: CI/CD 세팅
  .github/workflows/django.yml
Labels: enhancement

#115 :sparkles: Feat: CI/CD 세팅
  .github/workflows/django.yml
Labels: enhancement

#116 :bug: Fix: permission.py -> IsOwner 함수 에러 Fix
  utils/permissions.py
Labels: bug, enhancement

#117 🐛 Fix: permission.py -> IsOwner 함수 에러 Fix
  utils/permissions.py
Labels: bug

#118 🐛 Fix: permission.py -> IsOwner 함수 에러 Fix
  utils/permissions.py
Labels: bug

#121 :art: Style: 전체 코드 컨벤션, 파일명 수정
  README.md
  account/admin.py
  account/serializers.py
  account/urls.py
  account/views.py
  lodging/admin.py
  lodging/serializers.py
  lodging/tests/test_lodging_image.py
  lodging/tests/test_lodging_review.py
  lodging/tests/test_lodging_roomtype.py
  lodging/views.py
  nolreo_wassup/settings.py
  nolreo_wassup/wsgi.py
  pick/admin.py
  pick/models.py
  pick/serializers.py
  pick/views.py
  reservation/admin.py
  reservation/serializers.py
  static/assets/images/selfie/hwang.jpg
  static/assets/images/selfie/kang.jpg
  static/assets/images/selfie/lee.jpg
  traffic/tests/test_rentalcar.py
  utils/test_remove_tools.py
Labels: enhancement

#123 ✨ Feat: 전체 찜 목록 API & 🐛 Fix: 찜 요청 시 필요 사항 수정
  README.md
  account/tests.py
  lodging/admin.py
  lodging/serializers.py
  lodging/views.py
  pick/admin.py
  pick/models.py
  pick/serializers.py
  pick/tests.py
  pick/urls.py
  pick/views.py
  reservation/models.py
  traffic/admin.py
  traffic/serializers.py
Labels: enhancement

#126 :sparkles: Feat: swagger 적용 개발
  account/views.py
  lodging/serializers.py
  media/room_images/2023/12/24/lodging.jpg
  nolreo_wassup/settings.py
  nolreo_wassup/urls.py
  reservation/admin.py
Labels: enhancement

#129 :sparkles: Feat: 찜 목록 메서드 추가
  account/serializers.py
  lodging/serializers.py
  media/room_images/2023/12/24/lodging.jpg
  pick/views.py
Labels: enhancement

#128 ✨ Feat: 렌트카 리뷰 이미지 생성, 삭제 API 개발 및 테스트
  traffic/serializers.py
  traffic/tests/test_rentalcar.py
  traffic/urls.py
  traffic/views.py
Labels: enhancement

#132 :bug: Fix: 숙소 시리얼라이저 get_price 함수 에러 Fix
  lodging/serializers.py
  requirements.txt
Labels: bug

#133 :sparkles: Deploy: 배포 코드 최신화
  README.md
  account/admin.py
  account/serializers.py
  account/tests.py
  account/urls.py
  account/views.py
  lodging/admin.py
  lodging/serializers.py
  lodging/tests/test_lodging_image.py
  lodging/tests/test_lodging_review.py
  lodging/tests/test_lodging_roomtype.py
  lodging/views.py
  nolreo_wassup/settings.py
  nolreo_wassup/urls.py
  nolreo_wassup/wsgi.py
  pick/admin.py
  pick/models.py
  pick/serializers.py
  pick/tests.py
  pick/urls.py
  pick/views.py
  requirements.txt
  reservation/admin.py
  reservation/models.py
  reservation/serializers.py
  static/assets/images/deploy_architecture.png
  static/assets/images/selfie/hwang.jpg
  static/assets/images/selfie/kang.jpg
  static/assets/images/selfie/lee.jpg
  traffic/admin.py
  traffic/serializers.py
  traffic/tests/test_rentalcar.py
  traffic/urls.py
  traffic/views.py
  utils/test_remove_tools.py
Labels: enhancement

#134 :sparkles: Deploy: 배포 코드 최신화
  README.md
  account/admin.py
  account/serializers.py
  account/tests.py
  account/urls.py
  account/views.py
  lodging/admin.py
  lodging/serializers.py
  lodging/tests/test_lodging_image.py
  lodging/tests/test_lodging_review.py
  lodging/tests/test_lodging_roomtype.py
  lodging/views.py
  nolreo_wassup/settings.py
  nolreo_wassup/urls.py
  nolreo_wassup/wsgi.py
  pick/admin.py
  pick/models.py
  pick/serializers.py
  pick/tests.py
  pick/urls.py
  pick/views.py
  requirements.txt
  reservation/admin.py
  reservation/models.py
  reservation/serializers.py
  static/assets/images/deploy_architecture.png
  static/assets/images/selfie/hwang.jpg
  static/assets/images/selfie/kang.jpg
  static/assets/images/selfie/lee.jpg
  traffic/admin.py
  traffic/serializers.py
  traffic/tests/test_rentalcar.py
  traffic/urls.py
  traffic/views.py
  utils/test_remove_tools.py
Labels: enhancement

#136 ✨ Feat: lodging_serializers.py
  .gitignore
  account/admin.py
  lodging/serializers.py
  lodging/views.py
Labels: enhancement

#137 :sparkles: Feat: 검색을 위한 필터링 쿼리셋 추가
  lodging/serializers.py
  lodging/views.py
  traffic/serializers.py
  traffic/views.py
Labels: enhancement

#138 :bug: Fix: serializers.py 수정
  lodging/models.py
  lodging/serializers.py
  nolreo_wassup/settings.py
Labels: bug

#139 🐛 Fix: 선택된 숙소 리뷰 댓글 외 모든 댓글이 보이는 에러 수정
  lodging/views.py
  traffic/serializers.py
  traffic/views.py
Labels: enhancement

#143 :bug: Fix: account, lodging 수정
  account/serializers.py
  account/views.py
  lodging/serializers.py
Labels: bug

#146 :sparkles: Deploy: 최종 개발 배포
  .gitignore
  account/admin.py
  account/serializers.py
  account/views.py
  lodging/models.py
  lodging/serializers.py
  lodging/views.py
  nolreo_wassup/settings.py
  traffic/admin.py
  traffic/serializers.py
  traffic/views.py
Labels: enhancement

#152 :memo: Doc: README 수정
  README.md
  traffic/views.py
Labels: documentation

#153 📝 Doc: README 수정
  README.md
  traffic/views.py
Labels: documentation
